feat: created entities and seeding (#1)
- created entities and seeding

- add CI config with debug

- add improved commit hooks

- ci friendly  scripts

- fix: add [test] CDS profile to use in-memory SQLite during tests

- also normalized the file endings

- update adjust ignore files

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,5 @@
 #!/bin/sh
-
-prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
-git update-index --again
-
-npm run lint
+npx --no-install lint-staged || {
+  echo "lint-staged failed — see output above for failing files/lines."
+  exit 1
+}
